8339197: GenShen: Adding Generation and Evacuation Information JFR Logging
openjdk/shenandoah pull request #489
Opened 2024-08-28 22:43 UTC by satyenme

Adding `ShenandoahEvacInfo` event and modifying existing logging for Concurrent Reset and Final Roots events to include generation for Generational Shenandoah GC.

2024-08-29 00:06 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/heuristics/shenandoahGenerationalHeuristics.cpp
> +    ShenandoahTracer().report_evacuation_info(&evacInfo);
After we chatted, I thought of one other detail that would be nice to gather in this evacInfo event: regions to be promoted in place.  Associated with this detail, would be nice to know:
1. how many regions
2. how much garbage is known to exist within these regions
3. how much free memory is known to exist within these regions
Same for humongous regions promoted in place.

See humongous_regions_promoted, regular_regions_promoted_in_place, regular_regions_promoted_usage.   You might need to add another bookkeeping variable to count regular_regions_promoted_live, tracking regular_regions_promoted_usage.

2024-08-29 00:06 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/heuristics/shenandoahGenerationalHeuristics.cpp
> +    ShenandoahTracer().report_evacuation_info(&evacInfo);
for humongous_regions_promoted, less important to distinguish used and free, because that memory is "off limits" to allocators.

2024-08-29 00:06 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/shenandoahEvacInfo.hpp
> + * Copyright (c) 2013, 2021, Oracle and/or its affiliates. All rights reserved.
For these files introduced by us, we should put an Amazon copyright notice.  See, for example, shenandoahGenerationallHeuristics.cpp.

2024-08-30 17:59 UTC, kdnilsen approved these changes
Thanks for this code.  Let's get at least one other review before we integrate.

2024-08-30 18:02 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/shenandoahEvacInfo.hpp
> + * Copyright (c) 2013, 2021, Oracle and/or its affiliates. All rights reserved.
Thanks for fixing this

2024-08-30 18:02 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/heuristics/shenandoahGenerationalHeuristics.cpp
> +    ShenandoahTracer().report_evacuation_info(&evacInfo);
Looks good.

2024-08-30 18:34 UTC, earthling-amzn requested changes
Minor nits about missing newlines and suggest comment saying that all size values are words or bytes.

2024-08-30 18:34 UTC, earthling-amzn commented on src/hotspot/share/gc/shenandoah/shenandoahTrace.cpp
> +}
Missing newline.

2024-08-30 19:57 UTC, earthling-amzn approved these changes
Thank you!

2024-08-30 22:55 UTC, ysramakrishna approved these changes

2024-09-04 15:22 UTC, kdnilsen commented on src/hotspot/share/gc/shenandoah/shenandoahConcurrentGC.cpp
>    ShenandoahConcurrentPhase gc_phase(msg, ShenandoahPhaseTimings::conc_weak_refs);
Looks good.  With the "static" qualifier, the initialization statement only executes the first time through the function.

2024-09-04 16:00 UTC, satyenme commented
/integrate

2024-09-04 17:39 UTC, kdnilsen commented
/sponsor

2024-09-04 17:40 UTC, closed without merging