Check that pointer is in heap before checking the affiliation of owning region
openjdk/shenandoah pull request #52
Opened 2021-07-22 15:48 UTC by earthling-amzn

This is a small bug fix that was meant to go in with the concurrent remembered set scanning changes

2021-07-22 16:05 UTC, rkennke requested changes

2021-07-22 16:05 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahHeap.cpp
> +  return is_in(p) && heap_region_containing(p)->affiliation() == ShenandoahRegionAffiliation::YOUNG_GENERATION;
Is there a valid case where we would check off-heap pointers? If not, then better do this as assert?

2021-07-22 16:05 UTC, rkennke commented on src/hotspot/share/gc/shenandoah/shenandoahReferenceProcessor.cpp
> +  // that if the reference is not dropped, then its pointer to the referent will be cleared before
Those changes seem unrelated.

2021-07-22 17:30 UTC, earthling-amzn commented on src/hotspot/share/gc/shenandoah/shenandoahReferenceProcessor.cpp
> +  // that if the reference is not dropped, then its pointer to the referent will be cleared before
Will revert this change.

2021-08-06 13:51 UTC, rkennke approved these changes
Ok.

2021-08-06 16:18 UTC, earthling-amzn commented
/integrate

2021-08-06 16:20 UTC, closed without merging