8344260: GenShen: Excess unaffiliated regions reserved for old will not be transferred to young
openjdk/shenandoah pull request #538
Opened 2024-11-15 00:41 UTC by earthling-amzn

Accidental assignment to new (and unread) variable.

2024-11-15 02:08 UTC, ysramakrishna approved these changes

2024-11-15 02:08 UTC, ysramakrishna commented on src/hotspot/share/gc/shenandoah/shenandoahGeneration.cpp
> +    regions_to_xfer = MIN2(excess_regions, unaffiliated_old_regions);
Yikes! Thanks for finding this!

Did it make any difference to performance? Say with SPECjbb, e.g.?

2024-11-15 10:25 UTC, shipilev approved these changes

2024-11-15 10:26 UTC, shipilev requested changes
There are lots of crashes on related assert after this, I think.

2024-11-15 16:05 UTC, kdnilsen approved these changes

2024-11-18 10:21 UTC, shipilev approved these changes

2024-11-18 16:48 UTC, earthling-amzn commented
/integrate

2024-11-18 16:49 UTC, closed without merging